## YAML Template.
---
email:
  memberships: jasenhakemus@raisionveneseura.fi
  office: toimisto@raisionveneseura.fi
  memberships_requests: toimisto@raisionveneseura.fi
  webadmin: webadmin@raisionveneseura.fi
  jasenhakemus: toimisto@raisionveneseura.fi
  toimisto: toimisto@raisionveneseura.fi
  samiholck: sami.holck@gmail.com
