## YAML Template.
---
email:
  memberships: jasenhakemus@raisionveneseura.fi
  office: toimisto@raisionveneseura.fi
  memberships_requests: sami.holck@gmail.com
  webadmin: webadmin@raisionveneseura.fi
  
